# This is the main configuration file for PaperSpigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to PaperSpigot,
# join us at the IRC.
# 
# IRC: #paperspigot @ irc.spi.gt ( http://irc.spi.gt/iris/?channels=PaperSpigot )

config-version: 6
effect-modifiers:
  strength: 0.4
  weakness: -0.5
stackable-buckets:
  lava: false
  water: false
  milk: false
settings:
  async-plugin-bad-magic-catcher: true
  baby-zombie-movement-speed: 0.5
  limit-player-interactions: true
max-packets-per-player: 1000
world-settings:
  default:
    verbose: true
    tick-next-tick-list-cap: 10000
    tick-next-tick-list-cap-ignores-redstone: false
    keep-spawn-loaded: true
    disable-thunder: true
    falling-blocks-collide-with-signs: false
    use-async-lighting: true
    inverted-daylight-detectors: false
    water-over-lava-flow-speed: 5
    game-mechanics:
      disable-end-credits: true
      boats-drop-boats: false
      less-picky-torch-placement: false
      disable-player-crits: false
    allow-undead-horse-leashing: true
    nether-ceiling-void-damage: true
    remove-invalid-mob-spawner-tile-entities: true
    max-growth-height:
      cactus: 3
      reeds: 3
    optimize-explosions: true
    generator-settings:
      canyon: true
      caves: true
      dungeon: true
      fortress: true
      mineshaft: true
      stronghold: false
      temple: true
      village: true
      flat-bedrock: true
    tnt-entity-height-nerf: 0.0
    despawn-ranges:
      soft: 28
      hard: 98
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 900
    squid-spawn-height:
      minimum: 45.0
      maximum: 63.0
    player-exhaustion:
      block-break: 0.025
      swimming: 0.015
    load-chunks:
      enderpearls: false
      tnt-entities: false
      falling-blocks: false
    remove-unloaded:
      enderpearls: true
      tnt-entities: true
      falling-blocks: true
    lava-flow-speed:
      normal: 30
      nether: 10
    fast-drain:
      lava: false
      water: false
