# This is the main configuration file for Spigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# For a reference for any variable inside this file, check out the Spigot wiki at
# http://www.spigotmc.org/wiki/spigot-configuration/
# 
# If you need help with the configuration or have any questions related to Spigot,
# join us at the IRC or drop by our forums and leave a post.
# 
# IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )
# Forums: http://www.spigotmc.org/

config-version: 8
settings:
  debug: false
  disable:
    general:
      entity-collisions: false
      sleepcheck: false
    ticking:
      villages: false
      blocks: false
      weather: false
    entityTracking: false
    player-list-packets: false
    ping-update-packets: false
  save-user-cache-on-stop-only: false
  disableSaving: false
  smeltingMultiplier: 1
  brewingMultiplier: 1
  moved-too-quickly-threshold: 100.0
  chunkio:
    players-per-thread: 150
  autosave:
    fire-WorldSaveEvent: false
    chunks-per-tick: 200
    clear-RegionFileCache: false
  lagSpikeLogger:
    enabled: true
    tickLimitInMilliseconds: 100
  filter-creative-items: true
  moved-wrongly-threshold: 0.0625
  reduce-armor-damage: true
  player-shuffle: 0
  user-cache-size: 1000
  int-cache-limit: 1024
  bungeecord: true
  late-bind: true
  sample-count: 12
  global-api-cache: false
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
  netty-threads: 4
  pearl-through-tripwire: true
  disable-player-file-saving: false
  timeout-time: 10
  restart-on-crash: true
  restart-script: ./start.sh
  only-custom-tab: false
  cache-chunk-maps: false
  instantRespawn: false
  logRemainingAsyncThreadsDuringShutdown: true
commands:
  tab-complete: 0
  silent-commandblock-console: false
  spam-exclusions:
  - /skill
  log: true
  replace-commands:
  - setblock
  - summon
  - testforblock
  - tellraw
messages:
  restart: Server is restarting
  whitelist: You are not whitelisted on this server!
  unknown-command: Unknown command. Type "/help" for help.
  server-full: The server is full!
  outdated-client: Outdated client! Please use {0}
  outdated-server: Outdated server! I'm still on {0}
world-settings:
  default:
    verbose: true
    view-distance: 10
    mobs-enabled: true
    chunks-per-tick: 650
    clear-tick-list: false
    merge-radius:
      exp: 6.0
      item: 3.5
    enable-zombie-pigmen-portal-spawns: true
    wither-spawn-sound-radius: 0
    item-despawn-rate: 5000
    exp-despawn-rate: 6000
    arrow-despawn-rate: 300
    hanging-tick-frequency: 100
    useAlternateEndSpawn: true
    zombie-aggressive-towards-villager: true
    seed-village: 10387312
    seed-feature: 14357617
    max-entity-collisions: 6
    dragon-death-sound-radius: 0
    updateMapItemsInPlayerInventory: false
    enderPearlsCanPassNonSolidBlocks: false
    mob-spawn-range: 5
    anti-xray:
      enabled: false
      engine-mode: 1
      hide-blocks:
      - 14
      - 15
      - 16
      - 21
      - 48
      - 49
      - 54
      - 56
      - 73
      - 74
      - 82
      - 129
      - 130
      replace-blocks:
      - 1
      - 5
    growth:
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      wheat-modifier: 100
    save-structure-info: true
    entity-activation-range:
      animals: 32
      monsters: 32
      misc: 16
    hopper-alt-ticking: false
    ticks-per:
      hopper-transfer: 8
      hopper-check: 8
    hopper-amount: 1
    max-bulk-chunks: 5
    random-light-updates: false
    nerf-spawner-mobs: true
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 16
      other: 64
    hunger:
      walk-exhaustion: 0.2
      sprint-exhaustion: 0.6
      combat-exhaustion: 0.3
      regen-exhaustion: 2.4
    max-tnt-per-tick: 100
stats:
  forced-stats: {}
